export default [
  { city: 'Montgomery', state: 'Alabama', capital: true },
  { city: 'Juneau', state: 'Alaska', capital: true },
  { city: 'Phoenix', state: 'Arizona', capital: true },
  { city: 'Little Rock', state: 'Arkansas', capital: true },
  { city: 'Sacramento', state: 'California', capital: true },
  { city: 'Denver', state: 'Colorado', capital: true },
  { city: 'Hartford', state: 'Connecticut', capital: true },
  { city: 'Dover', state: 'Delaware', capital: true },
  { city: 'Tallahassee', state: 'Florida', capital: true },
  { city: 'Atlanta', state: 'Georgia', capital: true },
  { city: 'Honolulu', state: 'Hawaii', capital: true },
  { city: 'Boise', state: 'Idaho', capital: true },
  { city: 'Springfield', state: 'Illinois', capital: true },
  { city: 'Indianapolis', state: 'Indiana', capital: true },
  { city: 'Des Moines', state: 'Iowa', capital: true },
  { city: 'Topeka', state: 'Kansas', capital: true },
  { city: 'Frankfort', state: 'Kentucky', capital: true },
  { city: 'Baton Rouge', state: 'Louisiana', capital: true },
  { city: 'Augusta', state: 'Maine', capital: true },
  { city: 'Annapolis', state: 'Maryland', capital: true },
  { city: 'Boston', state: 'Massachusetts', capital: true },
  { city: 'Lansing', state: 'Michigan', capital: true },
  { city: 'Saint Paul', state: 'Minnesota', capital: true },
  { city: 'Jackson', state: 'Mississippi', capital: true },
  { city: 'Jefferson City', state: 'Missouri', capital: true },
  { city: 'Helena', state: 'Montana', capital: true },
  { city: 'Lincoln', state: 'Nebraska', capital: true },
  { city: 'Carson City', state: 'Nevada', capital: true },
  { city: 'Concord', state: 'New Hampshire', capital: true },
  { city: 'Trenton', state: 'New Jersey', capital: true },
  { city: 'Santa Fe', state: 'New Mexico', capital: true },
  { city: 'Albany', state: 'New York', capital: true },
  { city: 'Raleigh', state: 'North Carolina', capital: true },
  { city: 'Bismarck', state: 'North Dakota', capital: true },
  { city: 'Columbus', state: 'Ohio', capital: true },
  { city: 'Oklahoma City', state: 'Oklahoma', capital: true },
  { city: 'Salem', state: 'Oregon', capital: true },
  { city: 'Harrisburg', state: 'Pennsylvania', capital: true },
  { city: 'Providence', state: 'Rhode Island', capital: true },
  { city: 'Columbia', state: 'South Carolina', capital: true },
  { city: 'Pierre', state: 'South Dakota', capital: true },
  { city: 'Nashville', state: 'Tennessee', capital: true },
  { city: 'Austin', state: 'Texas', capital: true },
  { city: 'Salt Lake City', state: 'Utah', capital: true },
  { city: 'Montpelier', state: 'Vermont', capital: true },
  { city: 'Richmond', state: 'Virginia', capital: true },
  { city: 'Olympia', state: 'Washington', capital: true },
  { city: 'Charleston', state: 'West Virginia', capital: true },
  { city: 'Madison', state: 'Wisconsin', capital: true },
  { city: 'Cheyenne', state: 'Wyoming', capital: true },
];